import type {
  DemoScenario,
  GeneratedQuestion,
  GraphData,
  Memo,
  QueryResult,
} from "../types";

/** Call Foundry agent to generate interconnected memos for a scenario. */
export async function generateMemos(
  scenario: DemoScenario,
  count: number,
): Promise<Memo[]> {
  // TODO: POST ${API_BASE}/build/generate { scenario, count }
  console.log("[api] generateMemos placeholder:", scenario, count);
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    title: `Memo ${i + 1}`,
    content: `[Placeholder] This memo will be generated by a Foundry agent for the "${scenario}" scenario.`,
    date: new Date(2025, 0, 1 + i).toISOString().slice(0, 10),
  }));
}

/** Trigger GraphRAG indexing on the generated memos. */
export async function indexMemos(memos: Memo[]): Promise<GraphData> {
  // TODO: POST ${API_BASE}/build/index { memos }
  console.log("[api] indexMemos placeholder:", memos.length, "memos");
  return {
    nodes: memos.map((m) => ({
      id: `memo-${m.id}`,
      name: m.title,
      type: "concept" as const,
      description: m.content.slice(0, 60),
    })),
    links: memos.slice(1).map((m, i) => ({
      source: `memo-${memos[i].id}`,
      target: `memo-${m.id}`,
      label: "related to",
    })),
  };
}

/** Generate curated questions from the newly-built graph. */
export async function generateBuildQuestions(
  graph: GraphData,
): Promise<GeneratedQuestion[]> {
  // TODO: POST ${API_BASE}/build/questions { graph summary / community reports }
  console.log(
    "[api] generateBuildQuestions placeholder:",
    graph.nodes.length,
    "nodes",
  );
  return [
    { question: "What are the key themes across all memos?", type: "global" },
    {
      question: "Which people appear in multiple memos and why?",
      type: "cross-document",
    },
    {
      question: "What hidden connection exists between the memos?",
      type: "hidden",
    },
    { question: "How did the situation evolve over time?", type: "timeline" },
  ];
}

/** Query the build-tab graph with GraphRAG. */
export async function queryBuildGraph(question: string): Promise<QueryResult> {
  // TODO: POST ${API_BASE}/build/query { question }
  console.log("[api] queryBuildGraph placeholder:", question);
  return {
    answer:
      "Build-graph query placeholder — will show GraphRAG answer over the freshly-indexed memos.",
    citations: ["Entities (1, 2, 3)", "Reports (1)"],
  };
}
